// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcJNNXgwgdDJZx3GUtxMRA8XYERwsUZMQ',
    appId: '1:57345410832:web:2fc4ec7f0d5d8206ec0795',
    messagingSenderId: '57345410832',
    projectId: 'io-test-31f99',
    authDomain: 'io-test-31f99.firebaseapp.com',
    storageBucket: 'io-test-31f99.appspot.com',
    measurementId: 'G-06XSCXCF0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmup_DwK8K3PEzUcFLlu4ut5XKgrCWWt8',
    appId: '1:57345410832:android:a8dd3e614c2c7bf3ec0795',
    messagingSenderId: '57345410832',
    projectId: 'io-test-31f99',
    storageBucket: 'io-test-31f99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXD37x2FEEKp4bb1UY0eNT2hJZeGon-fE',
    appId: '1:57345410832:ios:9a697f34498b91a5ec0795',
    messagingSenderId: '57345410832',
    projectId: 'io-test-31f99',
    storageBucket: 'io-test-31f99.appspot.com',
    iosClientId: '57345410832-uo4mmk8cgua36gc37ku3k056ljafble5.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXD37x2FEEKp4bb1UY0eNT2hJZeGon-fE',
    appId: '1:57345410832:ios:9a697f34498b91a5ec0795',
    messagingSenderId: '57345410832',
    projectId: 'io-test-31f99',
    storageBucket: 'io-test-31f99.appspot.com',
    iosClientId: '57345410832-uo4mmk8cgua36gc37ku3k056ljafble5.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment2',
  );
}
